
deployment:
    tasks:
      - export DEPLOYPATH=/home/jasminedeveloper/sparepart.jasminedeveloper.com
      - /bin/cp -R * $DEPLOYPATH
      - /bin/cp -R ./spart-part/public/* $DEPLOYPATH/
   
      #composer install?
